// Code generated by gocc; DO NOT EDIT.

package lexer

/*
Let s be the current state
Let r be the current input rune
transitionTable[s](r) returns the next state.
*/
type TransitionTable [NumStates]func(rune) int

var TransTab = TransitionTable{
	// S0
	func(r rune) int {
		switch {
		case r == 48: // ['0','0']
			return 1
		case r == 49: // ['1','1']
			return 2
		case r == 50: // ['2','2']
			return 3
		case 51 <= r && r <= 57: // ['3','9']
			return 4
		}
		return NoState
	},
	// S1
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 5
		}
		return NoState
	},
	// S2
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 5
		case 48 <= r && r <= 57: // ['0','9']
			return 6
		}
		return NoState
	},
	// S3
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 5
		case 48 <= r && r <= 52: // ['0','4']
			return 7
		case r == 53: // ['5','5']
			return 8
		case 54 <= r && r <= 57: // ['6','9']
			return 1
		}
		return NoState
	},
	// S4
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 5
		case 48 <= r && r <= 57: // ['0','9']
			return 1
		}
		return NoState
	},
	// S5
	func(r rune) int {
		switch {
		case r == 48: // ['0','0']
			return 9
		case r == 49: // ['1','1']
			return 10
		case r == 50: // ['2','2']
			return 11
		case 51 <= r && r <= 57: // ['3','9']
			return 12
		}
		return NoState
	},
	// S6
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 5
		case 48 <= r && r <= 57: // ['0','9']
			return 1
		}
		return NoState
	},
	// S7
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 5
		case 48 <= r && r <= 57: // ['0','9']
			return 1
		}
		return NoState
	},
	// S8
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 5
		case 48 <= r && r <= 52: // ['0','4']
			return 13
		case r == 53: // ['5','5']
			return 14
		}
		return NoState
	},
	// S9
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 15
		}
		return NoState
	},
	// S10
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 15
		case 48 <= r && r <= 57: // ['0','9']
			return 16
		}
		return NoState
	},
	// S11
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 15
		case 48 <= r && r <= 52: // ['0','4']
			return 17
		case r == 53: // ['5','5']
			return 18
		case 54 <= r && r <= 57: // ['6','9']
			return 9
		}
		return NoState
	},
	// S12
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 15
		case 48 <= r && r <= 57: // ['0','9']
			return 9
		}
		return NoState
	},
	// S13
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 5
		}
		return NoState
	},
	// S14
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 5
		}
		return NoState
	},
	// S15
	func(r rune) int {
		switch {
		case r == 48: // ['0','0']
			return 19
		case r == 49: // ['1','1']
			return 20
		case r == 50: // ['2','2']
			return 21
		case 51 <= r && r <= 57: // ['3','9']
			return 22
		}
		return NoState
	},
	// S16
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 15
		case 48 <= r && r <= 57: // ['0','9']
			return 9
		}
		return NoState
	},
	// S17
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 15
		case 48 <= r && r <= 57: // ['0','9']
			return 9
		}
		return NoState
	},
	// S18
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 15
		case 48 <= r && r <= 52: // ['0','4']
			return 23
		case r == 53: // ['5','5']
			return 24
		}
		return NoState
	},
	// S19
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 25
		}
		return NoState
	},
	// S20
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 25
		case 48 <= r && r <= 57: // ['0','9']
			return 26
		}
		return NoState
	},
	// S21
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 25
		case 48 <= r && r <= 52: // ['0','4']
			return 27
		case r == 53: // ['5','5']
			return 28
		case 54 <= r && r <= 57: // ['6','9']
			return 19
		}
		return NoState
	},
	// S22
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 25
		case 48 <= r && r <= 57: // ['0','9']
			return 19
		}
		return NoState
	},
	// S23
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 15
		}
		return NoState
	},
	// S24
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 15
		}
		return NoState
	},
	// S25
	func(r rune) int {
		switch {
		case r == 48: // ['0','0']
			return 29
		case r == 49: // ['1','1']
			return 30
		case r == 50: // ['2','2']
			return 31
		case 51 <= r && r <= 57: // ['3','9']
			return 32
		}
		return NoState
	},
	// S26
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 25
		case 48 <= r && r <= 57: // ['0','9']
			return 19
		}
		return NoState
	},
	// S27
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 25
		case 48 <= r && r <= 57: // ['0','9']
			return 19
		}
		return NoState
	},
	// S28
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 25
		case 48 <= r && r <= 52: // ['0','4']
			return 33
		case r == 53: // ['5','5']
			return 34
		}
		return NoState
	},
	// S29
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S30
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		}
		return NoState
	},
	// S31
	func(r rune) int {
		switch {
		case 48 <= r && r <= 52: // ['0','4']
			return 36
		case r == 53: // ['5','5']
			return 37
		case 54 <= r && r <= 57: // ['6','9']
			return 29
		}
		return NoState
	},
	// S32
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 29
		}
		return NoState
	},
	// S33
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 25
		}
		return NoState
	},
	// S34
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 25
		}
		return NoState
	},
	// S35
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 29
		}
		return NoState
	},
	// S36
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 29
		}
		return NoState
	},
	// S37
	func(r rune) int {
		switch {
		case 48 <= r && r <= 52: // ['0','4']
			return 38
		case r == 53: // ['5','5']
			return 39
		}
		return NoState
	},
	// S38
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S39
	func(r rune) int {
		switch {
		}
		return NoState
	},
}
