// https://datatracker.ietf.org/doc/html/rfc3986#section-3.2.2
// https://datatracker.ietf.org/doc/html/rfc4234

// DIGIT       = 0-9

_digit         : '0' - '9';
_digit1        : '1' - '9';
_digit04       : '0' - '4';

// HEXDIG      =  DIGIT / "A" / "B" / "C" / "D" / "E" / "F"

// examples include lower case hexes fd7a:115c:a1e0:ab12:4843:cd96:626b:430b
_hexdig        : _digit | 'A' - 'F' | 'a' - 'f' ;

// dec-octet   = DIGIT                 ; 0-9
//             / %x31-39 DIGIT         ; 10-99
//             / "1" 2DIGIT            ; 100-199
//             / "2" %x30-34 DIGIT     ; 200-249
//             / "25" %x30-35          ; 250-255

_decoctet      : _digit
               | _digit1
               | '1' _digit _digit
               | '2' _digit04 _digit
               | '2' '5' _digit04
               | '2' '5' '5'
               ;

// IPv4address = dec-octet "." dec-octet "." dec-octet "." dec-octet

_ipv4          : _decoctet '.' _decoctet '.' _decoctet '.' _decoctet ;

// 1*<element> requires at least one, 3*3<element> allows exactly 3 and 1*2<element> allows one or two.
// h16         = 1*4HEXDIG
//             ; 16 bits of address represented in hexadecimal

_h16           : _hexdig
               | _hexdig _hexdig
               | _hexdig _hexdig _hexdig
               | _hexdig _hexdig _hexdig _hexdig
               ;

// ls32        = ( h16 ":" h16 ) / IPv4address
//            ; least-significant 32 bits of address
// examples include ::ffff:192.168.140.255, which has an ipv4
// We do not create the ls32 rule, since it causes conflicts between ::ffff:192.168.140.255 and ::192.168.140.255

// IPv6address =                            6( h16 ":" ) ls32
_ipv6nodolon   : _h16 ':' _h16 ':' _h16 ':' _h16 ':' _h16 ':' _h16 ':' _h16 ':' _h16
               | _h16 ':' _h16 ':' _h16 ':' _h16 ':' _h16 ':' _h16 ':' _ipv4
               ;

//             /                       "::" 5( h16 ":" ) ls32
_ipv6dolon5    : ':' ':' _h16 ':' _h16 ':' _h16 ':' _h16 ':' _h16  ':' _h16 ':' _h16
               | ':' ':' _h16 ':' _h16 ':' _h16 ':' _h16 ':' _h16  ':' _ipv4
               ;

//             / [               h16 ] "::" 4( h16 ":" ) ls32
_ipv6dolon4    :                       ':' ':' _h16 ':' _h16 ':' _h16 ':' _h16 ':' _h16 ':' _h16
               |                       ':' ':' _h16 ':' _h16 ':' _h16 ':' _h16 ':' _ipv4
               | _h16                  ':' ':' _h16 ':' _h16 ':' _h16 ':' _h16 ':' _h16 ':' _h16
               | _h16                  ':' ':' _h16 ':' _h16 ':' _h16 ':' _h16 ':' _ipv4
               ;

//             / [ *1( h16 ":" ) h16 ] "::" 3( h16 ":" ) ls32
_ipv6dolon3    :                       ':' ':' _h16 ':' _h16 ':' _h16 ':' _h16 ':' _h16 
               |                       ':' ':' _h16 ':' _h16 ':' _h16 ':' _ipv4 
               |          _h16         ':' ':' _h16 ':' _h16 ':' _h16 ':' _h16 ':' _h16 
               |          _h16         ':' ':' _h16 ':' _h16 ':' _h16 ':' _ipv4 
               | _h16 ':' _h16         ':' ':' _h16 ':' _h16 ':' _h16 ':' _h16 ':' _h16 
               | _h16 ':' _h16         ':' ':' _h16 ':' _h16 ':' _h16 ':' _ipv4 
               ;

//             / [ *2( h16 ":" ) h16 ] "::" 2( h16 ":" ) ls32
_ipv6dolon2    :  _h16 ':' _h16 ':' _h16             ':' ':' _h16 ':' _h16 ':' _h16 ':' _h16 
               |  _h16 ':' _h16 ':' _h16             ':' ':' _h16 ':' _h16 ':' _ipv4 
               |           _h16 ':' _h16             ':' ':' _h16 ':' _h16 ':' _h16 ':' _h16 
               |           _h16 ':' _h16             ':' ':' _h16 ':' _h16 ':' _ipv4 
               |                    _h16             ':' ':' _h16 ':' _h16 ':' _h16 ':' _h16 
               |                    _h16             ':' ':' _h16 ':' _h16 ':' _ipv4 
               |                                     ':' ':' _h16 ':' _h16 ':' _h16 ':' _h16 
               |                                     ':' ':' _h16 ':' _h16 ':' _ipv4 
               ;

//             / [ *3( h16 ":" ) h16 ] "::" h16 ":" ls32
_ipv6dolon1    :  _h16 ':' _h16 ':' _h16 ':' _h16    ':' ':' _h16 ':' _h16 ':' _h16 
               |  _h16 ':' _h16 ':' _h16 ':' _h16    ':' ':' _h16 ':' _ipv4 
               |           _h16 ':' _h16 ':' _h16    ':' ':' _h16 ':' _h16 ':' _h16 
               |           _h16 ':' _h16 ':' _h16    ':' ':' _h16 ':' _ipv4 
               |                    _h16 ':' _h16    ':' ':' _h16 ':' _h16 ':' _h16 
               |                    _h16 ':' _h16    ':' ':' _h16 ':' _ipv4 
               |                             _h16    ':' ':' _h16 ':' _h16 ':' _h16 
               |                             _h16    ':' ':' _h16 ':' _ipv4 
               |                                     ':' ':' _h16 ':' _h16 ':' _h16
               |                                     ':' ':' _h16 ':' _ipv4
               ;

//             / [ *4( h16 ":" ) h16 ] "::" ls32
_ipv6dolon0ls32 :  _h16 ':' _h16 ':' _h16 ':' _h16 ':' _h16          ':' ':' _h16 ':' _h16 
               |  _h16 ':' _h16 ':' _h16 ':' _h16 ':' _h16          ':' ':' _ipv4 
               |           _h16 ':' _h16 ':' _h16 ':' _h16           ':' ':' _h16 ':' _h16 
               |           _h16 ':' _h16 ':' _h16 ':' _h16           ':' ':' _ipv4 
               |                    _h16 ':' _h16 ':' _h16           ':' ':' _h16 ':' _h16 
               |                    _h16 ':' _h16 ':' _h16           ':' ':' _ipv4 
               |                             _h16 ':' _h16           ':' ':' _h16 ':' _h16 
               |                             _h16 ':' _h16           ':' ':' _ipv4 
               |                                      _h16           ':' ':' _h16 ':' _h16 
               |                                      _h16           ':' ':' _ipv4 
               |                                                     ':' ':' _h16 ':' _h16
               |                                                     ':' ':' _ipv4
               ;

//             / [ *5( h16 ":" ) h16 ] "::" h16
_ipv6dolon0h16 :  _h16 ':' _h16 ':' _h16 ':' _h16 ':' _h16 ':' _h16  ':' ':' _h16 
               |  _h16 ':' _h16 ':' _h16 ':' _h16 ':' _h16 ':' _h16  ':' ':' _h16 
               |           _h16 ':' _h16 ':' _h16 ':' _h16 ':' _h16  ':' ':' _h16 
               |           _h16 ':' _h16 ':' _h16 ':' _h16 ':' _h16  ':' ':' _h16 
               |                    _h16 ':' _h16 ':' _h16 ':' _h16  ':' ':' _h16 
               |                    _h16 ':' _h16 ':' _h16 ':' _h16  ':' ':' _h16 
               |                             _h16 ':' _h16 ':' _h16  ':' ':' _h16 
               |                             _h16 ':' _h16 ':' _h16  ':' ':' _h16 
               |                                      _h16 ':' _h16  ':' ':' _h16 
               |                                      _h16 ':' _h16  ':' ':' _h16 
               |                                               _h16  ':' ':' _h16 
               |                                               _h16  ':' ':' _h16 
               |                                                     ':' ':' _h16 
               |                                                     ':' ':' _h16 
               ;

//             / [ *6( h16 ":" ) h16 ] "::"
_ipv6dolon0    :  _h16 ':' _h16 ':' _h16 ':' _h16 ':' _h16 ':' _h16 ':' _h16 ':' ':' 
               |  _h16 ':' _h16 ':' _h16 ':' _h16 ':' _h16 ':' _h16 ':' _h16 ':' ':' 
               |           _h16 ':' _h16 ':' _h16 ':' _h16 ':' _h16 ':' _h16 ':' ':' 
               |           _h16 ':' _h16 ':' _h16 ':' _h16 ':' _h16 ':' _h16 ':' ':' 
               |                    _h16 ':' _h16 ':' _h16 ':' _h16 ':' _h16 ':' ':' 
               |                    _h16 ':' _h16 ':' _h16 ':' _h16 ':' _h16 ':' ':' 
               |                             _h16 ':' _h16 ':' _h16 ':' _h16 ':' ':' 
               |                             _h16 ':' _h16 ':' _h16 ':' _h16 ':' ':' 
               |                                      _h16 ':' _h16 ':' _h16 ':' ':' 
               |                                      _h16 ':' _h16 ':' _h16 ':' ':' 
               |                                               _h16 ':' _h16 ':' ':' 
               |                                               _h16 ':' _h16 ':' ':' 
               |                                                        _h16 ':' ':' 
               |                                                        _h16 ':' ':' 
               |                                                             ':' ':' 
               |                                                             ':' ':' 
               ;

ipv6           : _ipv6nodolon
               | _ipv6dolon5
               | _ipv6dolon4
               | _ipv6dolon3
               | _ipv6dolon2
               | _ipv6dolon1
               | _ipv6dolon0ls32
               | _ipv6dolon0h16
               | _ipv6dolon0
               ;
