name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: gopath/src/github.com/katydid/validator-go-jsonschema
    - name: Checkout testsuite
      uses: actions/checkout@v4
      with:
        repository: katydid/testsuite
        path: gopath/src/github.com/katydid/testsuite
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.23
    - name: Fetch dependencies
      run: |
        cd gopath/src/github.com/katydid/validator-go-jsonschema
        go mod download -x
    - name: Install tools
      run: |
        cd gopath/src/github.com/katydid/validator-go-jsonschema
        go install -x github.com/goccmack/gocc
        go install -x github.com/awalterschulze/goderive
        go install -x github.com/awalterschulze/checklicense
    - name: env
      run: env && go env && pwd
    - name: tree
      run: tree
    - name: Generate
      run: |
        cd gopath/src/github.com/katydid/validator-go-jsonschema
        PATH=$HOME/bin:$PATH make regenerate
    - name: Build
      run: |
        cd gopath/src/github.com/katydid/validator-go-jsonschema
        make build
    - name: Test
      run: |
        cd gopath/src/github.com/katydid/validator-go-jsonschema
        make test
    - name: Vet
      run: |
        cd gopath/src/github.com/katydid/validator-go-jsonschema
        make vet
    - name: Checklicencse
      run: |
        cd gopath/src/github.com/katydid/validator-go-jsonschema
        make checklicense
    - name: Diff
      run: |
        cd gopath/src/github.com/katydid/validator-go-jsonschema
        make diff